### ISSUE TITLE
[Feature Request]: Prevent dismissing of in-app message when clicking outside of the message

### ISSUE THREAD

**Issue by samatar26** [Iterable/iterable-web-sdk#137]
Helloooo 👋🏾 

# Issue
I'm currently using the web-sdk to show in-app messages in my project. With my in-app message however I have got a dedicated close button and I would therefore not like the user to dismiss the message by clicking anywhere outside of the message. The danger in this is if the user is heavily clicking around and therefore unintentionally closes the pop-up without having viewed the message.

# Proposed/Possible solution
You could maybe expose this as a configuration value in the `getInAppMessages` call

Thank you so much for looking into this!

**Comment by ahendricks** [comment]
Thanks for the suggestion @samatar26! Makes a lot of sense. We'll get this into our backlog!

**Comment by ahendricks** [comment]
Hi @samatar26, we've added this capability in our latest release, v0.4.0. Let us know if you have any feedback!
