### ISSUE TITLE
`updateEmail` failure returns same response code for email in use and jwt error

### ISSUE THREAD

**Issue by danwbyrne** [Iterable/iterable-web-sdk#158]
Currently in the web-sdk we will receive the following error responses from the `updateEmail` function:

1. the email is already in use - we receive status code 400 and a message {"msg":"Cannot change user <uid> to <email>. New email already exists","code":"EmailAlreadyExists","params":null} - its worth noting here that we don't have access to this message from the response callback of the `updateEmail` function
2. the JWT token is not authorized - we receive status code 400 and a JWT specific error message

This means we have no way to distinguish when we can ignore the call (the email already exists we just ignore the response) and when we need to refresh our jwt token.

**Comment by martinmckenna** [comment]
hey @danwbyrne, the error shape is an `AxiosError`, so when you are catching your promise errors you can get access to the Iterable response like so:

```ts
import { AxiosError } from 'axios'
import { IterableErrorStatus } from '@iterable/web-sdk';

updateUserEmail(...args)
  .then((response) => response)
  .catch((error: AxiosError) => {
    const iterableCode: IterableErrorStatus = error.response.data.code;

    if (!!iterableCode.match(/emailalreadyexists/gi)) {
      /* do something */
    }

    if (!!iterableCode.match(/jwt/gi)) {
      /* do something else */
    }
  });
```

Also just FYI, the SDK will try to get a new JWT for you and retry the original failed request automatically if you get a `401` response, as [documented here](https://github.com/Iterable/iterable-web-sdk#what-if-my-jwt-expires), but it sounds like you're getting a `400` for a bad JWT?

**Comment by danwbyrne** [comment]
Thanks for this, closing the issue
