### ISSUE TITLE
Function `initialize()` called without JWT returns undefined

### ISSUE THREAD

**Issue by charlesfries** [Iterable/iterable-web-sdk#195]
```
"@iterable/web-sdk": "^1.0.1",
```

I am attempting to migrate my web app away from the static Iterable analytics/utilities SDK files to this package.

With the static JS my code previously looked like this:

```js
const iterableId = '...'; // using real (non JWT) api key

window.iterableAnalytics.account(iterableId);
window.iterableAnalytics.identify('example@example.com');
window.iterableAnalytics.track('myEvent', {});
```

With `@iterable/web-sdk`, my code now looks like this:

```js
import { initialize, track } from '@iterable/web-sdk';

const iterableId = '...';

const { setEmail } = initialize(iterableId);
setEmail('example@example.com');
track({ eventName: 'myEvent' });
```

However when I call `initialize()` the function returns an undefined value, when it should return `WithoutJWT`. And therefore I cannot call `setEmail()`.

I know the documentation does say to create an API token with JWT enabled, but is the non-signed functionality still available in this package, as I believe it was in the static JS API? Or do I absolutely need a signed key on the frontend?

Any help would be appreciated. Thanks. Really appreciate the work done to create this TS package.

**Comment by mprew97** [comment]
Hey @charlesfries, you do need a signed key/jwt in order to use this SDK. We should at least return an error in the initialize method if no JWT is provided.
