### ISSUE TITLE
[Question] Safari support with trackInAppClick()

### ISSUE THREAD

**Issue by Mapsai** [Iterable/iterable-web-sdk#236]
Hello.

I have a question. I'm using `getInAppMessages` with in-app method to show modals inside a webpage. Everything is fine but for Safari I see that `trackInAppClick` is not fired (looking through network). Based on the following link: https://github.com/Iterable/iterable-web-sdk#api this behavior is known.

My question: is there a fix or ideas how to make sure in-app click works on Safari as well? Or do I need to create my own workaround for that (like onClick listener, etc.)?

Appreciated!

**Comment by mprew97** [comment]
Hi @Mapsai, onClick handler more than likely won't work as Safari doesn't support event handlers with our current i-frame security policy.
