### ISSUE TITLE
filterHiddenInAppMessages doesn't work with a JSON only message

### ISSUE THREAD

**Issue by finnhom** [Iterable/iterable-web-sdk#237]
It's not possible to use the built in `filterHiddenInAppMessages` method when using  JSON only in-app message. This is because there is a check to make sure the html exists for every message, which it won't if it's a JSON only message (`!!eachMessage.content?.html`). Is this supposed to work like this? If so would it be possible to add a method that works with JSON only messages?

https://github.com/Iterable/iterable-web-sdk/blob/6e4f8eb7d6264e7dc835e1137ffd269beadef6d0/src/inapp/utils.ts#L111-L121

**Comment by mprew97** [comment]
Hey @finnhom, thanks for bringing this up. I'll bring this question up to our product teams and see how we should approach addressing it!

**Comment by mprew97** [comment]
After thinking on this some, we can just create a separate method. Considered changing the filter logic there but some users may be dependent on that logic remaining consistent so makes more sense to build a separate method entirely.

**Comment by finnhom** [comment]
Thanks for the swift response and work on this @mprew97!

**Comment by mprew97** [comment]
Hey @finnhom just merged this! Will cut a release here in a bit. You will need to install that updated package in order to use the new method :)

**Comment by finnhom** [comment]
Amazing, thank you

**Comment by mprew97** [comment]
@finnhom apologies on the delay of the release. Install the most recent npm package to access that method.
