### ISSUE TITLE
Dependency Updates

### ISSUE THREAD

**Issue by lernerb** [Iterable/iterable-web-sdk#244]
Hey @mprew97 - do ya'll and the rest of iterable plan on updating most of the moderate/critical security dependencies against the iterable-web-sdk? It's one of the only libraries left in our react app that has a ton of updated vulnerabilities, and our compliance team is asking us to upgrade as we're in the finance world. We would like to avoid manually patching so many updates, as it's usually simpler for the dependency to keep up to date with min versions.

* https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
* https://github.com/advisories/GHSA-j8xg-fqg3-53r7
* https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

Please let us know.

**Comment by mprew97** [comment]
Hey @lernerb! We do actually have it on our roadmap. Are these the main vulnerabilities brought up by your compliance team?

**Comment by lernerb** [comment]
Those are the only three that the current dependency rules aren't overriding due to package rules (e.g. ~/^)!

I'd highly recommend if possible to keep dependencies up to date based on Dependabot and to enable repo Security checks - it'll tell ya'll when there are security advisories and will attempt to do the first patch. (and it makes your life easier when there's a major breaking change - to not be so far behind).

Thanks for responding so quickly!

**Comment by mprew97** [comment]
Will work with the team to get this prioritized for our next sprint.

**Comment by mprew97** [comment]
created an item to pull this into our next sprint

**Comment by thebiltheory** [comment]
@lernerb The package is open-source, PR's are always welcome.

**Comment by mprew97** [comment]
Hey Lerner, just an update here: 

The Axio security issue has been fixed. You can pull the latest release for that one. There is a separate PR I have open to resolve a bunch of other outdated dependency and security issues [here](https://github.com/Iterable/iterable-web-sdk/pull/246).

**Comment by lernerb** [comment]
Thank you @mprew97 - we've updated on our end and see it as fixed as well! We are able to locally patch over the second PR while we wait for that to get merged as well.
